{
tempo_execucao_script: "0hs 2min 1seg",
project_id: "time-traiket",
id_filtro_redmine: "8813",
id_filtro_redmine_tag: "8814",
leadtime_dias: 13.17,
leadtime: "13 dias 4h 3' ",
cycletime_desenvolvimento: "4 dias 14h 9' ",
cycletime_novo_aberto: "1 dias 5h 17' ",
cycletime_homologacao: "11 dias 15h 18' ",
cycletime_resolvido_fechado: "8 dias 22h 45' ",
qtd_chamados_leadtime: 1353,
qtd_chamados_novo_resolvido: 1144,
qtd_chamados_homologa_validado: 294,
qtd_chamados_resolvido_fechado: 1144,
qtd_chamados_rejeitados: 73,
qtd_chamados_rejeitados_Indevidos: 11,
qtd_chamados_rejeitados_Real: 62,
taxa_rejeicao: "4.58%",
tem_rejeicao: 0,
tem_cancelamento: 0,
tem_impedimento: 1,
tem_Liberado: 0
}